export const categoriesConfig = {
  immobilier: {
    label: "Immobilier",
    filters: [
      // ✅ NOUVEAU FILTRE : Type de vente
      {
        name: "ventesetlocations",
        label: "Ventes et locations",
        type: "select",
        options: [
          { value: "ventes", label: "Ventes" },
          { value: "locations", label: "Locations" },
        ],
      },
      // ✅ NOUVEAU FILTRE : Type Annonces
      {
        name: "typeannonces",
        label: "Type d’annonces",
        type: "select", // car une seule option peut être sélectionnée
        options: [
          { value: "offres", label: "Offres" },
          { value: "demandes", label: "Demandes" },
        ],
      },
      // ✅ NOUVEAU FILTRE : Tri
      {
        name: "tri", // ← NOUVEAU FILTRE
        label: "Tri",
        type: "select",
        options: [
          { value: "pertinence", label: "Pertinence" },
          { value: "recent", label: "Plus récentes" },
          { value: "ancien", label: "Plus anciennes" },
          { value: "price-asc", label: "Prix croissants" },
          { value: "price-desc", label: "Prix décroissants" },
        ],
      },

      // ✅ NOUVEAU FILTRE : Avec ascenseur
      {
        name: "avecascenseur", // ← NOUVEAU FILTRE
        label: "Avec ascenseur",
        type: "select",
        options: [
          {
            value: "annoncesavecascenseuruniquement",
            label: "Annonces avec ascenseur uniquement",
          },
        ],
      },
      // ✅ NOUVEAU FILTRE : Étage de l'appartement
      {
        name: "etageappartement", // ← NOUVEAU FILTRE
        label: "Étage de l'appartement",
        type: "select",
        options: [
          { value: "rez-de-chaussee", label: "Rez-de-chaussée" },
          { value: "pas-rez-de-chaussee", label: "Pas de rez-de-chaussée" },
          { value: "dernier-etage", label: "Dernier étage" },
        ],
      },
      // ✅ NOUVEAU FILTRE : Pieces
      {
        name: "chambres",
        label: "Chambres",
        type: "range", // ← garder "range" pour qu'il soit reconnu
        minName: "chambresMin", // ← ajouter explicitement
        maxName: "chambresMax", // ← ajouter explicitement
      },
      // ✅ NOUVEAU FILTRE : Pieces
      {
        name: "rooms",
        label: "Nombre de pièces",
        type: "range", // ← garder "range" pour qu'il soit reconnu
        minName: "roomsMin", // ← ajouter explicitement
        maxName: "roomsMax", // ← ajouter explicitement
      },
      // ✅ NOUVEAU FILTRE : Surface terrain
      {
        name: "surfaceterrain",
        label: "Surface du terrain",
        type: "surfaceterrain",
        placeholderMin: "Min (m²)",
        placeholderMax: "Max (m²)",
        unit: "m²",
      },
      // ✅ NOUVEAU FILTRE : Surface habitable
      {
        name: "surface",
        label: "Surface habitable",
        type: "surface",
        placeholderMin: "Min (m²)",
        placeholderMax: "Max (m²)",
        unit: "m²",
      },
      // ✅ NOUVEAU FILTRE : Surface Bureaux Commerces
      {
        name: "surfacebureauxcommerces",
        label: "Surface",
        type: "surfacebureauxcommerces",
        placeholderMin: "Min (m²)",
        placeholderMax: "Max (m²)",
        unit: "m²",
      },
      // ✅ NOUVEAU FILTRE :Loyer
      {
        name: "loyer", // Nom utilisé dans l'URL et les états
        label: "Loyer",
        type: "loyer", // On définit un type personnalisé pour le reconnaître
        placeholderMin: "Minimum",
        placeholderMax: "Maximum",
        icon: "€", // Symbole de la devise
      },
      // ✅ NOUVEAU FILTRE : Prix
      {
        name: "price", // Nom utilisé dans l'URL et les états
        label: "Prix",
        type: "price", // On définit un type personnalisé pour le reconnaître
        placeholderMin: "Minimum",
        placeholderMax: "Maximum",
        icon: "€", // Symbole de la devise
      },
      // ✅ NOUVEAU FILTRE : Type de bien
      {
        name: "typebien",
        label: "Type de bien",
        type: "select",
        order: 4,
        options: [
          { value: "maison", label: "Maison" },
          { value: "appartement", label: "Appartement" },
          { value: "terrain", label: "Terrain" },
          { value: "parking", label: "Parking" },
          { value: "chambre", label: "Chambre" },
          { value: "studio", label: "Studio" },
          { value: "autre", label: "Autre" },
        ],
      },
      // ✅ NOUVEAU FILTRE : Etat du bien
      {
        name: "etatdubien", // ← NOUVEAU FILTRE
        label: "État du bien",
        type: "select",
        order: 5,
        options: [
          { value: "tres-bon-etat", label: "Très bon état" },
          { value: "bon-etat", label: "Bon état" },
          { value: "renove", label: "Rénové" },
          { value: "a-rafraichir", label: "À rafraîchir" },
          { value: "travaux-a-prevoir", label: "Travaux à prévoir" },
        ],
      },
      // ✅ NOUVEAU FILTRE : Type de vente
      {
        name: "typevente",
        label: "Type de vente",
        type: "select",
        order: 6,
        options: [
          { value: "ancien", label: "Ancien" },
          { value: "neuf", label: "Neuf" },
          { value: "viager", label: "Viager" },
        ],
      },
      // ✅ NOUVEAU FILTRE : Meublés
      {
        name: "meuble",
        label: "Meublé / Non meublé",
        type: "select",
        options: [
          { value: "meuble", label: "Meublé" },
          { value: "nonmeuble", label: "Non meublé" },
        ],
      },
    ],
    defaultExcludeFilters: ["ventesetlocations"], // ← vos choix
    subcategories: {
      "ventes-immobilieres": {
        label: "Ventes immobilières",
        // types supprimé
        excludeFilters: [
          "meuble",
          "ventesetlocations",
          "surfacebureauxcommerces",
        ], // ← Ajoutez cette ligne
      },
      "immobilier-neuf": {
        label: "Immobilier neuf",
        // types supprimé

        excludeFilters: ["typevente", "loyer", "ventesetlocations"],
      },
      locations: {
        label: "Locations",
        // types supprimé
        filters: [],
        excludeFilters: [
          "price",
          "typevente",
          "etatdubien",
          "ventesetlocations",
          "surfacebureauxcommerces",
        ], // ← Ajoutez cette ligne
      },
      colocations: {
        label: "Colocations",
        excludeFilters: [
          "price",
          "meuble",
          "surfaceterrain",
          "typebien",
          "typevente",
          "ventesetlocations",
          "surfacebureauxcommerces",
        ], // ← Ajoutez cette ligne
      },
      "bureaux-commerces": {
        label: "Bureaux & Commerces",
        excludeFilters: [
          "rooms",
          "chambres",
          "typevente",
          "etatdubien",
          "meuble",
          "typebien",
          "surface",
          "surfaceterrain",
        ], // ← Ajoutez cette ligne
      },
    },
  },

  vehicules: {
    label: "Véhicules",

    filters: [
      // 🔥 Type d'annonce
      {
        name: "typeannonces",
        label: "Type d’annonces",
        type: "select",
        options: [
          { value: "offres", label: "Offres" },
          { value: "demandes", label: "Demandes" },
        ],
      },

      // 🔥 Tri
      {
        name: "tri",
        label: "Tri",
        type: "select",
        options: [
          { value: "pertinence", label: "Pertinence" },
          { value: "recent", label: "Plus récentes" },
          { value: "ancien", label: "Plus anciennes" },
          { value: "price-asc", label: "Prix croissants" },
          { value: "price-desc", label: "Prix décroissants" },
        ],
      },

      // 💰 Prix
      {
        name: "price",
        label: "Prix",
        type: "price",
        placeholderMin: "Minimum",
        placeholderMax: "Maximum",
        icon: "€",
      },

      // 📅 Année
      {
        name: "annee",
        label: "Année",
        type: "range",
        minName: "anneeMin",
        maxName: "anneeMax",
      },

      // 🚗 Kilométrage
      {
        name: "kilometrage",
        label: "Kilométrage",
        type: "range",
        minName: "kilometrageMin",
        maxName: "kilometrageMax",
      },

      // ⛽ Carburant
      {
        name: "carburant",
        label: "Carburant",
        type: "select",
        options: [
          { value: "essence", label: "Essence" },
          { value: "diesel", label: "Diesel" },
          { value: "electrique", label: "Électrique" },
          { value: "hybride", label: "Hybride" },
        ],
      },

      // ⚙️ Transmission
      {
        name: "boite",
        label: "Boîte de vitesse",
        type: "select",
        options: [
          { value: "manuelle", label: "Manuelle" },
          { value: "automatique", label: "Automatique" },
        ],
      },

      // 🧑‍🔧 État du véhicule
      {
        name: "etatvehicule",
        label: "État du véhicule",
        type: "select",
        options: [
          { value: "neuf", label: "Neuf" },
          { value: "tres-bon-etat", label: "Très bon état" },
          { value: "bon-etat", label: "Bon état" },
          { value: "a-reparer", label: "À réparer" },
        ],
      },

      // 👤 Type vendeur
      {
        name: "typevendeurs",
        label: "Type de vendeurs",
        type: "select",
        options: [
          { value: "particuliers", label: "Particuliers" },
          { value: "professionnels", label: "Professionnels" },
        ],
      },
    ],
    defaultExcludeFilters: ["annee", "kiometrage", "carburant", "boitevitesse"], // ← vos choix

    subcategories: {
      voitures: {
        label: "Voitures",
        // types supprimé
        excludeFilters: ["cylindree", "typemoto"], // ← Ajoutez cette ligne
      },

      motos: {
        label: "Motos",
        excludeFilters: [
          "mensualitefinancement",
          "typevehicule",
          "boitevitesse",
          "etatvehicule",
          "puissancefiscale",
          "nombreportes",
          "nombreplaces",
        ], // ❌ pas de boîte classique
      },

      caravaning: {
        label: "Caravaning",
        excludeFilters: [
          "boitevitesse",
          "couleur",
          "energie",
          "nombreportes",
          "nombreplaces",
          "typemoto",
          "puissancedin",
          "puissancefiscale",
          "cylindree",
          "mensualitefinancement",
          "marque", // ✅
          "modele", // ✅
          "finitions",
          "critair", // ✅ singulier
        ],
      },

      utilitaires: {
        label: "Utilitaires",
      },

      camions: {
        label: "Camions",
      },

      nautisme: {
        label: "Nautisme",
        excludeFilters: ["kilometrage", "boite"],
      },

      velos: {
        label: "Vélos",
        excludeFilters: ["carburant", "boite", "kilometrage"],
      },

      "equipement-auto": {
        label: "Équipement auto",
        excludeFilters: [
          "annee",
          "kilometrage",
          "carburant",
          "boite",
          "etatvehicule",
        ],
      },

      "equipement-moto": {
        label: "Équipement moto",
        excludeFilters: ["annee", "kilometrage", "carburant", "boite"],
      },

      "equipement-caravaning": {
        label: "Équipement caravaning",
        excludeFilters: [],
      },
      "equipement-nautisme": {
        label: "Équipement nautisme",
        excludeFilters: [],
      },
     
    },
  },

  emploi: {
    label: "Emploi",
    filters: [
      // 🔥 Type d'annonce
      {
        name: "typecontrat",
        label: "Type de contrat",
        type: "select",
        options: [
          { value: "cdd", label: "CDD" },
          { value: "cdi", label: "CDI" },
          { value: "interim", label: "Intérim" },
          { value: "independant-franchise", label: "Indépendant / Franchise" },
          {
            value: "apprentissage-alternance",
            label: "Apprentissage / Alternance",
          },
          { value: "stage", label: "Stage" },
          { value: "benevolat", label: "Bénévolat" },
        ],
      },
      // 🔥 Type d'annonce
      {
        name: "typeannonces",
        label: "Type d’annonces",
        type: "select",
        options: [
          { value: "offres", label: "Offres" },
          { value: "demandes", label: "Demandes" },
        ],
      },

      // 🔥 Tri
      {
        name: "tri",
        label: "Tri",
        type: "select",
        options: [
          { value: "pertinence", label: "Pertinence" },
          { value: "recent", label: "Plus récentes" },
          { value: "ancien", label: "Plus anciennes" },
          { value: "price-asc", label: "Prix croissants" },
          { value: "price-desc", label: "Prix décroissants" },
        ],
      },

      // 👤 Type vendeur
      {
        name: "typevendeurs",
        label: "Type de vendeurs",
        type: "select",
        options: [
          { value: "particuliers", label: "Particuliers" },
          { value: "professionnels", label: "Professionnels" },
        ],
      },
    ],
    defaultExcludeFilters: [""], // ← vos choix
    subcategories: {
      offres: {
        label: "Offres d'emploi",
        // types supprimé
        excludeFilters: ["eligiblecpf", "typeenseignement", "domaineformation"],
      },
      "formations-professionnelles": {
        label: "Formations professionnelles",
        // types supprimé
        excludeFilters: [
          "typecontrat",
          "secteuractivite",
          "fonction",
          "niveauetude",
          "tempspleintempspartiel",
          "experience",
        ],
      },
      "profil-candidat": {
        label: "Profil Candidat",
        // types supprimé
        excludeFilters: [
          "eligiblecpf",
          "typeenseignement",
          "domaineformation",
          "typecontrat",
          "secteuractivite",
          "fonction",
          "niveauetude",
          "tempspleintempspartiel",
          "experience",
        ],
      },
    },
  },

  vacances: {
    label: "Vacances",
    subcategories: {
      hebergements: {
        label: "Types d’hébergements",
      },
      caracteristiques: {
        label: "Caractéristiques recherchées",
      },
      voyageurs: {
        label: "Nombre de voyageurs",
      },
    },
  },

  mode: {
    label: "Mode",
    subcategories: {
      vetements: {
        label: "Vêtements",
        excludeFilters: [
          "universchaussures",
          "marquechaussures",
          "typechaussures",
          "produit",
          "universmontresbijoux",
          "matieremontresbijoux",
          "marquemontresbijoux",
          "produitaccessoiresbagagerie",
          "universaccessoiresbagagerie",
          "marqueaccessoiresbagagerie",
          "matiereaccessoiresbagagerie",
        ],
      },
      chaussures: {
        label: "Chaussures",
        excludeFilters: [
          "taille",
          "univers",
          "typevetement",
          "marquemode",
          "produit",
          "universmontresbijoux",
          "universmontresbijoux",
          "matieremontresbijoux",
          "marquemontresbijoux",
          "produitaccessoiresbagagerie",
          "universaccessoiresbagagerie",
          "marqueaccessoiresbagagerie",
          "matiereaccessoiresbagagerie",
        ],
      },
      "montres-bijoux": {
        label: "Montres & Bijoux",
        excludeFilters: [
          "taille",
          "univers",
          "typevetement",
          "marquemode",
          "universchaussures",
          "marquechaussures",
          "typechaussures",
          "couleur",
          "pointure",
          "produitaccessoiresbagagerie",
          "universaccessoiresbagagerie",
          "marqueaccessoiresbagagerie",
          "matiereaccessoiresbagagerie",
        ],
      },
      "accessoires-bagagerie": {
        label: "Accessoires & Bagagerie",
        excludeFilters: [
          "taille",
          "univers",
          "typevetement",
          "marquemode",
          "produit",
          "universchaussures",
          "marquechaussures",
          "typechaussures",
          "pointure",
          "universmontresbijoux",
          "matieremontresbijoux",
        ],
      },
    },
  },

  "maison-jardin": {
    label: "Maison & Jardin",
    subcategories: {
      ameublement: {
        label: "Ameublement",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
          "typeelectromenager",
        ],
      },
      "papeterie-fournitures-scolaires": {
        label: "Papeterie & Fournitures scolaires",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "couleur",
          "typeelectromenager",
        ],
      },

      electromenager: {
        label: "Électroménager",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "typedecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },

      "arts-table": {
        label: "Arts de la table",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "typedecoration",
          "typedeelectromenager",
          "typeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },

      decoration: {
        label: "Décoration",
        excludeFilters: [
          "typelinge",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "typeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },
      "linge-maison": {
        label: "Linge de maison",
        excludeFilters: [
          "styledecoration",
          "matieredecoration",
          "typedecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "typeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "couleur",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },
      bricolage: {
        label: "Bricolage",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "typedecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "typeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "couleur",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },
      "jardin-plantes": {
        label: "Jardin & Plantes",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "typedecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "typeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "couleur",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },
      "services-jardinerie-bricolage": {
        label: "Services de jardinerie & bricolage",
        excludeFilters: [
          "typelinge",
          "styledecoration",
          "matieredecoration",
          "typedecoration",
          "matieretable",
          "marqueartstable",
          "typeartstable",
          "typedeelectromenager",
          "typeelectromenager",
          "typeameublement",
          "matiereameublement",
          "marqueameublement",
          "couleur",
          "marquefournituresscolaires",
          "produitfournituresscolaires",
        ],
      },
    },
  },

  famille: {
    label: "Famille",
    subcategories: {
      "equipement-bebe": {
        label: "Équipement bébé",
        excludeFilters: [
          "typevetementbebe",
          "mobilierenfantetat",
          "mobilierenfantproduit",
          "vetementsbebetaille",
        ],
      },
      "mobilier-enfant": {
        label: "Mobilier enfant",
        excludeFilters: [
          "vetementsbebetaille",
          "typevetementbebe",
          "familleetat",
          "familleproduit",
          "famillemarque",
        ],
      },
      "vetements-bebe": {
        label: "Vêtements bébé",
        excludeFilters: [
          "mobilierenfantetat",
          "mobilierenfantproduit",
          "familleetat",
          "familleproduit",
          "famillemarque",
        ],
      },
    },
  },

  electronique: {
    label: "Électronique",
    subcategories: {
      ordinateurs: {
        label: "Ordinateurs",
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",
          "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",

          "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",
           "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",

          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusestailleecran",
          "tablettesliseusescouleur",
          "tablettesliseusescapacitestockage",
          "tablettesliseusesmarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
        ],
      },
      "accessoires-informatique": {
        label: "Accessoires informatique",
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",
          "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",

           "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",
           "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",


          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusescouleur",
          "tablettesliseusescapacitestockage",
          "tablettesliseusestailleecran",
          "tablettesliseusesmarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",
        ],
      },
      "tablettes-liseuses": {
        label: "Tablettes & Liseuses",
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",
          "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",

           "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",
           "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",


          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",
        ],
      },
      "photo-audio-video": {
        label: "Photo, audio & vidéo",
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",
           "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",

           "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",
           "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",


          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusesmarque",
          "tablettesliseusescouleur",
          "accessoiresinformatiqueproduit",
          "tablettesliseusescapacitestockage",
          "tablettesliseusestailleecran",
          "tablettesliseusesmarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",
        ],
      },
      "telephones-objets-connectes": {
        label: "Téléphones & objets connectés",
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",
          "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",

          "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",


          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusescouleur",
          "tablettesliseusescapacitestockage",
          "tablettesliseusestailleecran",
          "tablettesliseusesmarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",
        ],
      },
      "accessoires-téléphone-objets-connectés": {
        label: "Accessoires téléphone & Objets connectés",
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",

          "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",

           "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",


          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusescouleur",
          "tablettesliseusescapacitestockage",
          "tablettesliseusestailleecran",
          "tablettesliseusesmarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",

          



        ],
      },
      "consoles": {
        label: "Consoles", // je suis ici à consoles de zero
        
        excludeFilters: [
          "jeuxvideoplatforme",
          "jeuxvideoetat",


           "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",
           "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",


          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusescouleur",
          "tablettesliseusescapacitestockage",
          "tablettesliseusestailleecran",
          "tablettesliseusesmarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",
        ],
      },
      "jeux-video": {
        label: "Jeux vidéo",
        excludeFilters: [

          "consolestype",
          "consolesmarque",
          "consolesmodele",
          "consolescouleur",
          "consolesetat",



           "accessoirestelephoneobjetsconnectesproduit",
          "accessoirestelephoneobjetsconnectescouleur",
          "accessoirestelephoneobjetsconnectesetat",
           "telephonesobjetsconnectesmodele",
          "telephonesobjetsconnectesmarque",
          "telephonesobjetsconnectesproduit",
          "telephonesobjetsconnectescapacitestockage",
          "telephonesobjetsconnectescouleur",
          "telephonesobjetsconnectesetat",


          "photoaudiovideoetat",
          "photoaudiovideocouleur", 
          "photoaudiovideoproduit",
          "photoaudiovideomarque",
          "tablettesliseusesetat",
          "tablettesliseusesproduit",
          "tablettesliseusescouleur",
          "tablettesliseusescapacitestockage",
          "tablettesliseusestailleecran",
          "tablettesliseusesmarque",
          "accessoiresinformatiqueetat",
          "accessoiresinformatiqueproduit",
          "accessoiresinformatiquemarque",
          "ordinateurgeneraletat",
          "tailleecran",
          "ordinateurmarque",
          "ordinateurtype",
        ],
      },
    },
  },

  loisirs: {
    label: "Loisirs",
    subcategories: {
      
      antiquites: {
        label: "Antiquités",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","billeterietype","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat",],
      },
      "artistes-musiciens": {
        label: "Artistes & Musiciens",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      billetterie: {
        label: "Billetterie",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      collection: {
        label: "Collection",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "cd-musique": {
        label: "CD - Musique",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "dvd-films": {
        label: "DVD - Films",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "instruments-de-musique": {
        label: "Instruments de musique",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "livres": {
        label: "Livres",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "modelisme": {
        label: "Modélisme",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "vins-gastronomie": {
        label: "Vins & Gastronomie",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "jeux-jouets": {
        label: "Jeux & Jouets",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "sport-plein-air": {
        label: "Sport & Plein air",
        excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit",
          "dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },

      "loisirs-creatifs": {
        label: "Loisirs créatifs",
        excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","velosunivers",
"velostype",
"velostaillevelo",
"velostailletoue",
"velosmarque",
"veloscouleur",
"velosetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit",
          "dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },

      velos: {
        label: "Vélos",
         excludeFilters:["equipementvelosunivers",
"equipementvelosproduit",
"equipementvelosmarque",
"equipementvelostaille",
"equipementvelosetat","loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat",
          "instrumentsetat",
          "instrumentsniveau",
          "instrumentsmarque",
          "instrumentsunivers",
          "instrumentsproduit",


          "dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat"],
      },
      "equipements-velos": {
        label: "Équipements vélos",
         excludeFilters:["loisirscreatifsproduit",
"loisirscreatifscible",
"loisirscreatifsetat","sportpleinairactivite",
"sportpleinairtat","jeuxjouetsage",
"jeuxjouetsproduit",
"jeuxjouetsetat",
"jeuxjouetsmarque","vinsgastronomieunivers",
"vinsgastronomieetat","modelismeproduit",
"modelismeechelle",
"modelismemarque",
"modelismeetat","livresformat",
"livresgenre",
"livreslangue",
"livresetat","dvdfilmsupport",
"dvdfilmgenre",
"dvdfilmedition",
"dvdfilmpackaging",
"dvdfilmetat","collectionproduit",
"collectionepoque",
"collectionconditionnement",
"collectionetat","billeterietype","loisirsproduit","loisirsmaterie","loisirsepoque",
"loisirsstyle",
"loisirsetat","cdmusiquesupport",
"cdmusiquegenre",
"cdmusiqueetat",],
      },
    },
  },

  autres: {
    label: "Autres",
    filters: [
      // 🔥 Type d'annonce
      {
        name: "typeservices",
        label: "Type de services",
        type: "select",
        options: [
          { value: "services-demenagement", label: "Services de déménagement" },
          { value: "reparations-mecaniques", label: "Réparations mécaniques" },
        ],
      },
    ],
    defaultExcludeFilters: [], // ← vos choix
    subcategories: {
      "materiel-professionnel": {
        label: "Matériel professionnel",
      },
      services: {
        label: "Services",
      },
      animaux: {
        label: "Animaux",
      },
    },
  },
};
